### ISSUE TITLE
Est-ce toujours utilisable sur Laravel 5.5 et SystemPay 3.19 ?

### ISSUE THREAD

**Issue by CharlieEtienne** [restoore/laravel-systempay#1]
Bonjour,

Ce package est-il toujours opérationnel sur des versions plus récentes ?
Y'a t-il potentiellement des failles de sécurité ou des risques à l'utiliser aujourd'hui et dans le futur ?

Merci

**Comment by tovitch** [comment]
Bonjour,

Rapidement testé sur Laravel 5.6.34 et SystemPay 2.18.0 (?) en mode TEST. Il semble fonctionnel sauf sur deux points :

- Dans la méthode `set_amount`, les paramètres de la callback de `array_where` sont inversés.
- Dans la méthode `add_product`, le calcul et le cast d'amount ne se font pas dans le bon ordre (càd cast en int puis multiplié par 100)

A priori, pas de risques ni problème de sécurité à prévoir. Une signature basée sur les paramètres à envoyer et sur le certificat de test/product est générée donc si un utilisateur modifie une variable, le formulaire ne sera plus valide.

**Comment by restoore** [comment]
Salut,
Mon développement se base sur la version 3.12 de la documentation : https://systempay.cyberpluspaiement.com/html/Doc/Payment_Form/Guide_d_implementation_formulaire_paiement_Systempay_v3.20.pdf
Toutes les améliorations ou ajout qui ont été fait après ne sont pas pris en compte.
Merci tovitch pour ton retour, j'ai corrigé les fonction set_amount et add_product

**Comment by CharlieEtienne** [comment]
Merci à tous les deux de m'avoir répondu ! Et bravo pour ce package.
